// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANXTUvAI8Mr4oiyumY9RCi-D6YopUWpeI',
    appId: '1:38202768363:web:63f0ff15f9fdab7b1d37ae',
    messagingSenderId: '38202768363',
    projectId: 'ecommerce-final-project-3a0bd',
    authDomain: 'ecommerce-final-project-3a0bd.firebaseapp.com',
    storageBucket: 'ecommerce-final-project-3a0bd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqeDCkdrP4aLr6DgmscFJKGDuQw1V70G8',
    appId: '1:38202768363:android:f49c7831ab1721461d37ae',
    messagingSenderId: '38202768363',
    projectId: 'ecommerce-final-project-3a0bd',
    storageBucket: 'ecommerce-final-project-3a0bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxKEqcna83PhH7Qd45ET1NzyGjFqMAKgM',
    appId: '1:38202768363:ios:71785e7503d23a621d37ae',
    messagingSenderId: '38202768363',
    projectId: 'ecommerce-final-project-3a0bd',
    storageBucket: 'ecommerce-final-project-3a0bd.appspot.com',
    iosClientId: '38202768363-0md054ddlk1g2vgaptdctlisilq86k2q.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceFinalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxKEqcna83PhH7Qd45ET1NzyGjFqMAKgM',
    appId: '1:38202768363:ios:71785e7503d23a621d37ae',
    messagingSenderId: '38202768363',
    projectId: 'ecommerce-final-project-3a0bd',
    storageBucket: 'ecommerce-final-project-3a0bd.appspot.com',
    iosClientId: '38202768363-0md054ddlk1g2vgaptdctlisilq86k2q.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceFinalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANXTUvAI8Mr4oiyumY9RCi-D6YopUWpeI',
    appId: '1:38202768363:web:1e631dbbae1b5aa51d37ae',
    messagingSenderId: '38202768363',
    projectId: 'ecommerce-final-project-3a0bd',
    authDomain: 'ecommerce-final-project-3a0bd.firebaseapp.com',
    storageBucket: 'ecommerce-final-project-3a0bd.appspot.com',
  );

}